### ISSUE TITLE
Jest snapshot testing passing unique classNames

### ISSUE THREAD

**Issue by k15a** [styled-components/jest-styled-components#29] opened 2017-06-13 21:12 UTC
Moved form https://github.com/styled-components/styled-components/issues/916 by @corbanbrook

> Styled components generate a unique classname hash based on the style content and passes this classname to the snapshot. This causes snapshots to break when styles are adjusted.
> 
> I understand this might be useful if you want to break snapshots on style change or even show style diffs with the jest-styled-components plugin but by including the hashed classname it ends up not only breaking the snapshot of the changed component but also the snapshots of any components that wrap it. This can be a mild annoyance when adjusting a Button styling causes hundreds of snapshots all over the application to break because they included Button.
> 
> CSS Modules had a similar issue but solved it with the identity-obj-proxy lib and moduleNameMapper:
> 
>     "moduleNameMapper": {
>       "\\.(css)$": "identity-obj-proxy"
>      }
> which would convert className={styles.myStyle} to className="myStyle" in the snapshot rather than "myStyle-{unique-hash}".
> 
> Is there something similar for mocking in classnames for styled-components?

**Comment by geelen** [comment] 2017-06-15 00:15
Had another bug report similar to this, with a reproduction repo that I've figured out the problem for and left some description: https://github.com/JamieDixon/sc-jest-issue/issues/1

Basically, ordering causes classnames to jump around wildly unless you're using `babel-plugin-styled-components` in your jest test environment. Which kinda sucks, since the generated classnames should be free to change without invalidating your snapshot. So I'm not sure that that fix is appropriate, I think building something into this library that ignores classname churn would be better.

**Comment by MicheleBertoli** [comment] 2017-06-15 08:01
Thank you very much @philpl @k15a @geelen and @JamieDixon.

Given this:
> So, the bug is caused because the class names are influenced by the order in which the styled components are created. This is an unfortunate necessity, since we have nothing else to uniquely identify which component is which at runtime.

I strongly agree the problem should be fixed by this package.

**Comment by MicheleBertoli** [comment] 2017-06-18 10:30
I [implemented  a solution](https://github.com/styled-components/jest-styled-components/pull/31), which [seems to work](https://github.com/JamieDixon/sc-jest-issue/pull/2) as expected.
Feedback is welcome :)

**Comment by MicheleBertoli** [comment] 2017-07-15 11:35
🙌 v4 is out
Thanks to everyone!

**Closed by MicheleBertoli** 2017-07-15 11:35 UTC
Labels: enhancement
