### ISSUE TITLE
shared __snapshots__ on repo 

### ISSUE THREAD

**Issue by codeangler** [styled-components/jest-styled-components#46] opened 2017-07-14 20:12 UTC
This is a question.

When I switch to a team member's branch, then run test all snapshot test fail, after passing locally.  Though looking at the error it is just the class hash that's changed.   Should we be including or not including __snapshots__ to not be getting errors while using jest-styled-component for snapshots? or are we missusing  jest-styled-components

**Comment by MicheleBertoli** [comment] 2017-07-15 07:01
Hello @codeangler, you'll be happy to know that we are addressing the issue in #29 and the [solution](https://github.com/styled-components/jest-styled-components/pull/31) will be shipped over this weekend :)

**Comment by MicheleBertoli** [comment] 2017-07-15 07:02
Duplicate of #29

**Closed** 2017-07-15 07:02 UTC
