### ISSUE TITLE
Support styled-components v2

### ISSUE THREAD

**Issue by ismay** [styled-components/jest-styled-components#5] opened 2017-04-19 07:44 UTC
Since 1.4 is listed as a peerdependency I'm assuming it's only meant to work with v1. I'm asking because I'm using v2 and would like to use this lib as well, but I've been running into some issues (window is not defined on CI tests, even with `testEnvironment: node`). Wondering if that's expected because it isn't officially supported, or that I'm doing something wrong.

**Comment by MicheleBertoli** [comment] 2017-04-19 08:35
Hello @ismay, thanks for opening this issue.
At the moment this package only works with v1 (I didn't even try it with v2).

However, it's something I absolutely want to address in the near future.
I'm leaving this open until it's done, and PRs are more than welcome.

**Comment by ismay** [comment] 2017-04-20 12:38
Ok cool! I did try it with v2 btw, worked locally but interestingly it failed on travis. So it looked quite good already. I'll see what I can find after v2 has been released.

**Comment by Thr44** [comment] 2017-04-28 15:35
Hi, 

I'm getting an issue that an error is thrown, whether I use "testEnvironment": "node" or not, when I call :
`toMatchStyledComponentsSnapshot()` I get:

`TypeError: styleSheet.rules is not a function`

here's a complete test that is failing:

```
import React from 'react';
import renderer from 'react-test-renderer';
import styled from 'styled-components';

describe('styled Component Tests', () => {

  it('should render a styled h4', () => {
    const iconStyles = `
      margin-left: -2px;
      margin-right: 4px;
      margin-top: -3px;
    `;

    const H4 = styled.h4`${iconStyles}`;

    const container = renderer.create(
      <H4>"a label"</H4>
    ).toJSON();
    expect(container).toMatchStyledComponentsSnapshot();
  });
```

**Comment by philpl** [comment] 2017-04-28 15:47
This will need to be updated for the v2 StyleSheet that @geelen updated recently to support async SSR 🙃

**Comment by ismay** [comment] 2017-05-02 10:39
Ok so it seems that only [styleSheetSerializer](https://github.com/styled-components/jest-styled-components/blob/master/src/serializers/styleSheetSerializer.js) needs to be updated. Am I correct in assuming that [these two functions](https://github.com/styled-components/jest-styled-components/blob/master/src/serializers/styleSheetSerializer.js#L60-L61) need to be replaced by the [new api](https://sc-next-docs.philpl.com/docs/advanced#server-side-rendering) for capturing styles from `renderToString`?

**Comment by MicheleBertoli** [comment] 2017-05-03 20:18
Yes @ismay, I can confirm that the main idea is updating the SSR APIs.
I think the `node` environment is going to help with that.
Please let me know if you need any help.
Thank you very much!

**Comment by philpl** [comment] 2017-05-04 00:16
@MicheleBertoli the new StyleSheetManager might be able to help you since it'd allow you to separate stylesheets from one another extremely effortlessly.

I haven't looked through the code here yet, but does that sound helpful? You could also just use the context directly I guess

**Comment by MicheleBertoli** [comment] 2017-05-04 06:15
Thank you very much, @philpl. 
I'm sure is going to be straightforward with the new public APIs, I just didn't have time to do it :)
As far as I understand @ismay is working on it, otherwise I'll implement it on the weekend.

**Comment by ismay** [comment] 2017-05-04 08:19
> As far as I understand @ismay is working on it, otherwise I'll implement it on the weekend.

I was planning to, but don't have the time before the weekend. It's all yours :)!

**Comment by MicheleBertoli** [comment] 2017-05-04 08:34
Sounds perfect, thanks @ismay.
If you don't mind I'm going to ask you to review my code.

I might also ping @philpl for some help.

Have a lovely day!

**Comment by ismay** [comment] 2017-05-04 10:26
👍  No problem, I'd be happy to

> Have a lovely day!

You too!

**Comment by MicheleBertoli** [comment] 2017-05-07 07:23
I tried to run the package with Styled Components v2 (2.0.0-15) and, apart from a change in the class name (`className="sc-bdVaJa iATjrR"`), it works.
I guess we can close this for now, and support the v2 properly when it's stable.

**Comment by philpl** [comment] 2017-05-07 08:16
@MicheleBertoli <= 2.0.0-15 are unfortunately released with the old v2 StyleSheet API, but >= 2.0.0-16 have the new one and are our release candidates :/

https://github.com/styled-components/styled-components/tags

**Comment by MicheleBertoli** [comment] 2017-05-07 08:21
I see, thanks @philpl.
I run `yarn add styled-components@next` and I got `styled-components@2.0.0-15`.
This makes much more sense now :)

**Comment by philpl** [comment] 2017-05-07 08:59
@MicheleBertoli the RC should be on the @rc tag :)

**Comment by MicheleBertoli** [comment] 2017-05-07 09:25
Here we go #14 
Feedback are welcome :)

**Comment by Thr44** [comment] 2017-05-12 17:52
hi, lovely to see so many changes :) 
class name (className="sc-bdVaJa iATjrR") is still an issue, right?

**Comment by MicheleBertoli** [comment] 2017-05-14 15:24
I wouldn't define it an issue, but all the snapshots need to be updated when upgrading to v2.

**Closed** 2017-06-11 19:19 UTC
