### ISSUE TITLE
TypeErrors for `css.parse` and `css.apply` Issue with Enzyme

### ISSUE THREAD

**Issue by slipperypenguin** [styled-components/jest-styled-components#99] opened 2017-11-22 02:10 UTC
Hello,

I'm having trouble getting my Jest tests to pass with Enzyme after using `styled-components`.

The current errors being thrown are `TypeError: css.parse is not a function` and `TypeError: css.apply is not a function`. I've attached screenshots below to hopefully get some context. 

So far, I have tried most of the suggestions from [here](https://github.com/styled-components/styled-components/issues/624#issuecomment-298035669), from the `jest-styled-components` README, and the `styled-components` site. 

Current config:
`node`: 8.9.1
`npm`: 5.5.1
`enzyme`: ^3.2.0,
`enzyme-to-json`: ^3.2.2,
`babel-plugin-styled-components`: ^1.3.0,
`jest`: ^21.2.1,
`jest-styled-components`: ^4.9.0

Jest config in `package.json`
<img width="598" alt="screen shot 2017-11-21 at 9 03 58 pm" src="https://user-images.githubusercontent.com/3655354/33106348-a24b3f34-ceff-11e7-9adb-d636b036204e.png">

Error Screenshots:
<img width="490" alt="screen shot 2017-11-21 at 8 43 31 pm" src="https://user-images.githubusercontent.com/3655354/33106364-b3765e10-ceff-11e7-8c33-c3840eb8c1a6.png">

<img width="476" alt="screen shot 2017-11-21 at 8 45 40 pm" src="https://user-images.githubusercontent.com/3655354/33106377-c715a1ba-ceff-11e7-86f7-55ff04d87751.png">

**Comment by MicheleBertoli** [comment] 2017-11-25 11:39
Hello @slipperypenguin, thanks for opening the issue.
Unfortunately, I won't be able to help without seeing the implementation of the component and the test.
Would you be able to provide it?
Thanks!

**Comment by slipperypenguin** [comment] 2017-11-26 04:55
Hey @MicheleBertoli  thanks for the response!

Attached below are some screenshot's of the component and test implementation (trying to grab the really basic/small components & tests that are getting the issue)

`Box.jsx` file containing `styled-components`:
<img width="648" alt="screen shot 2017-11-25 at 8 52 16 pm" src="https://user-images.githubusercontent.com/3655354/33237235-f0a251ba-d23b-11e7-9121-7cbbc83196dc.png">


`ErrorPage.js` 
<img width="650" alt="screen shot 2017-11-25 at 8 42 09 pm" src="https://user-images.githubusercontent.com/3655354/33237191-bf636766-d23a-11e7-9c46-bc9f89de52ea.png">

<img width="591" alt="screen shot 2017-11-25 at 8 42 22 pm" src="https://user-images.githubusercontent.com/3655354/33237194-c47187f6-d23a-11e7-8d2a-e00c26c0559d.png">

`ErrorPage.test.js`
<img width="652" alt="screen shot 2017-11-25 at 8 40 54 pm" src="https://user-images.githubusercontent.com/3655354/33237209-08927616-d23b-11e7-9887-18363e0f05ea.png">

Hopefully these can help with finding the issue. Please let me know if more examples or context is needed.

**Comment by MicheleBertoli** [comment] 2017-11-26 08:11
Thank you very much @slipperypenguin for providing more information.
First of all, in future issues I recommend you copy the code in the comments - text is more useful than screenshots because the code can be copied and pasted into the editor.

Second, unfortunately I don't see anything wrong with your code and I didn't manage to reproduce the same behaviour. 

Some more questions for you here:
- Are you using the latest version of the Styled Components? 
- Do the tests work if you remove `jest-styled-components`?
- Is this code available somewhere on GitHub where I can debug it? or, would you be able to push a minimal non-working example?

**Comment by slipperypenguin** [comment] 2017-11-26 22:52
@michalkvasnicak thanks for the feedback- will post text instead of screenshots:)

It looks like the issue has to do with the `styled-components` package and not the `jest-styled-components` one, since I'm still getting the same errors after removing the package. I'll try getting a minimal example pushed, as well as bring the issue up in the `styled-components` repo.

Once the issue is solved I'll be sure to post here in-case someone else has a similar problem.

**Comment by MicheleBertoli** [comment] 2017-12-02 10:39
I'm closing this for now since it's unrelated to this package, feel free to ping me if you need any help and please let me know what is the cause of the issue if you manage to fix it.
Thank you very much!

**Closed by MicheleBertoli** 2017-12-02 10:39 UTC
