### ISSUE TITLE
Cannot create styled-component for component: undefined

### ISSUE THREAD

**Issue by prasanth95** [styled-components/jest-styled-components#114] opened 2018-01-23 04:30 UTC
The test case failed by showing this error

 ● Test suite failed to run

    Cannot create styled-component for component: undefined
      
      at constructWithOptions (node_modules/styled-components/lib/constructors/constructWithOptions.js:17:7)
      at styled (node_modules/styled-components/lib/native/index.js:45:8)
      at Function.get [as Text] (node_modules/styled-components/lib/native/index.js:59:8)
      at Object.<anonymous> (app/Common/styledComponents/Text/FormLabelText/index.js:8:36)
      at Object.<anonymous> (app/Common/components/TextInputField/index.js:26:20)

**Comment by MicheleBertoli** [comment] 2018-01-24 15:28
Duplicate of #105

**Closed by MicheleBertoli** 2018-01-24 15:28 UTC
