### ISSUE TITLE
Work with react-testing-library

### ISSUE THREAD

**Issue by albert-olive** [styled-components/jest-styled-components#163] opened 2018-07-24 06:22 UTC
Hi, I'm facing an issue with the snapshots using react-testing-library. This is the [issue](https://github.com/kentcdodds/react-testing-library/issues/144).

At the end, Kent is saying that your snapshot serializer doesn't work for DOM elements like glamorous and emotion do.

He points out what he did: https://github.com/kentcdodds/jest-glamor-react/blob/61cb3d0d7acef4f34128a7d3a75f60ebc97730e2/src/serializer.js#L75-L101

Thanks

**Comment by keul** [comment] 2018-08-01 10:43
See also #129

**Comment by MicheleBertoli** [comment] 2018-08-09 12:28
Hey @albert-olive, I confirm this library works with components rendered using the `react-test-renderer` and `enzyme`.
It would be nice to support DOM elements, and the `react-testing-library`.
Would you be happy to submit a PR?
Thank you very much!

**Comment by MicheleBertoli** [comment] 2018-08-09 12:31
Duplicate of #129

**Closed** 2018-08-09 12:31 UTC
