### ISSUE TITLE
Error: "Could neither find styled-components secret internals" when import

### ISSUE THREAD

**Issue by Duncan00** [styled-components/jest-styled-components#301] opened 2020-01-24 11:04 UTC
In a jest test:
```
import 'jest-styled-components';
```
When run test, will get error:
```
Could neither find styled-components secret internals
```
Versions:
```
"styled-components": "4.2.0"
"jest-styled-components": "7.0.0"
```

Similar issue here: https://stackoverflow.com/questions/59860271/could-neither-find-styled-components-secret-internals

Thanks!

**Comment by valentinbourqui** [comment] 2020-01-24 15:37
There is already a ticket  #297

**Comment by kachkaev** [comment] 2020-01-24 15:39
Duplicate of #297

**Closed** 2020-01-24 15:39 UTC

**Comment by PravallikaVinod** [comment] 2020-04-20 04:42
@Duncan00 Is above issue solved?

**Comment by santanapaulo** [comment] 2020-06-05 20:38
As mentioned on this comment https://github.com/styled-components/jest-styled-components/issues/315#issuecomment-628014081, if you guys update your styled-component lib to some version higher than >5.0.0, it should work.

I was having the same issue, and it worked well to me.

**Comment by vanduc1102** [comment] 2021-08-05 05:13
There is a warning when i have `"styled-components": "4.4.1",` and run yarn add `yarn add jest-styled-components`  
`warning " > jest-styled-components@7.0.5" has incorrect peer dependency "styled-components@>= 5".`

Change to `yarn add  jest-styled-components@5.0.0` solve the issue.
