### ISSUE TITLE
Issue with CircleCI

### ISSUE THREAD

**Issue by lgraziani2712** [styled-components/jest-styled-components#44] opened 2017-07-11 19:37 UTC
Hello, I'm having trouble with the snapshot testing and I don't know what to do 😭.

Dependencies:

- styled-components@2.1.1 (also tried with @2.1.0)
- babel-plugin-styled-components@1.1.7 (also tried with @1.1.4)
- jest@20.0.4
- jest-styled-components@3.3.1 (also tried with @3.1.2)

In my own PC (win10) it works everything OK. But when CircleCI executes the tests, it throws the following diff:

```diff
- .hvMUct > img {
-   filter: drop-shadow(-2px 2px 2px rgba(0, 0, 0, 0.5));
+ .lihsux > img {
+   filter: drop-shadow(-2px 2px 2px rgba(0,0,0,0.5));
}
```

Every `,{blank}` space are stripped everywhere QQ

Thank you for your work :)

**Comment by MicheleBertoli** [comment] 2017-07-12 14:52
Interesting, thanks @lgraziani2712.
I've never seen anything similar, I'll investigate further and let you know.

**Comment by MicheleBertoli** [comment] 2017-07-12 14:58
Interesting, thanks @lgraziani2712.
I'm sorry you're having trouble with the package.
I've never seen anything similar, I'll investigate further and let you know.
Any additional information, repro steps or code examples are more than welcome.

**Comment by MicheleBertoli** [comment] 2017-07-12 14:59
Interesting, thanks @lgraziani2712.
I'm sorry you are having troubles with the package.
I've never seen anything similar, I'll investigate further and let you know.
Any additional information, repro steps or code examples are more than welcome.

**Comment by lgraziani2712** [comment] 2017-07-12 20:13
Thank you for your response @MicheleBertoli!

This is the latest failing CI report: https://circleci.com/gh/lgraziani2712/codimo/26
The following code is from this file: https://github.com/lgraziani2712/codimo/blob/master/src/components/FrontPage.jsx#L36

```jsx
const WhiteRow = styled(Row)`
  background: white;
  box-shadow: 0 0 4px 4px rgba(85, 95, 110, 0.4);
  justify-content: flex-start;
  position: relative;
  z-index: 1;
  & > img {
    filter: drop-shadow(-2px 2px 2px rgba(0, 0, 0, 0.5));
  }
`;
```

This is the Snapshot result from my PC:

```css
.hvMUct {
  background: white;
  box-shadow: 0 0 4px 4px rgba(85, 95, 110, 0.4);
  -webkit-box-pack: start;
  -webkit-justify-content: flex-start;
  -ms-flex-pack: start;
  justify-content: flex-start;
  position: relative;
  z-index: 1;
}

.hvMUct > img {
  filter: drop-shadow(-2px 2px 2px rgba(0, 0, 0, 0.5));
}
```

I tried deleting my node_modules and the CI's cache.

**Comment by MicheleBertoli** [comment] 2017-07-16 09:45
Hello @lgraziani2712, I found out that the root cause is the minifcation process of [babel-plugin-styled-components](https://github.com/styled-components/babel-plugin-styled-components).
I [opened a PR](https://github.com/lgraziani2712/codimo/pull/45) on the original repo for your convenience, feel free to merge or close it.
Also, you should upgrade `jest-styled-components` to v4 to avoid the class name issue.

**Closed by MicheleBertoli** 2017-07-16 09:45 UTC

**Comment by bessey** [comment] 2017-07-20 22:38
This also bit me, on Travis. I'd like to understand the root cause so I can patch `babel-plugin-styled-components` to not behave differently between dev and CI. @MicheleBertoli do you know where in `babel-plugin-styled-components` a different path is being taken on CI? I can't see any references to `process.env` in their repo, so not sure what they're doing?

**Comment by MicheleBertoli** [comment] 2017-07-21 08:10
@bessey it very likely has something to do with the configuration, all the options should be in the `.babelrc`.
