### ISSUE TITLE
toHaveStyleRule TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by RIP21** [styled-components/jest-styled-components#26] opened 2017-06-12 17:58 UTC
I'm trying to test whether the component has `display:inline` when horizontal is set to true.
Here is the component code:
```javascript
export const StyledLabel = styled.label`
  display: block;
  ${props => props.horizontal && css`
      display: inline;
  `}
  & i {
    color: red;
  }
  ${props => props.css}
`;
```
And here is the test:
```javascript
import { StyledLabel } from "./Label";
import React from "react";
import { mount } from "enzyme";

test("when horizontal must be display:inline", () => {
  //given
  const text = "text";
  //when
  const component = mount(<StyledLabel horizontal>{text}</StyledLabel>);
  //then
  expect(component).toHaveStyleRule("display", "inline");
});
```

But at the end I got an error:
```
 FAIL  src\components\Label\index.test.js
  ● <Label /> › when horizontal must be display:inline

    TypeError: Cannot read property '1' of null

      at message (node_modules/jest-styled-components/src/matchers/toHaveStyleRule.js:79:48)
      at Object.it (src/components/Label/index.test.js:73:23)
          at Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:169:7)

```

I have `"jest-styled-components": "^3.0.0"` and `"styled-components": "^2.0.0"` and latest CRA.

**Comment by leocreatini** [comment] 2017-06-12 18:42
I was able to get passing test with it:
```js
import styled, { css } from 'styled-components' // ^2.0.0
import { mount } from 'enzyme'  // ^2.8.2
import 'jest-styled-components' // 3.0.0

test('enzyme', () => {
  const StyledLabel = styled.label`
    display: block;
    ${props => props.horizontal && css`
        display: inline;
    `}
    & i {
      color: red;
    }
    ${props => props.css}
  `
  const wrapper = mount(<StyledLabel horizontal>Hello World</StyledLabel>)

  expect(wrapper).toHaveStyleRule('display', 'inline')
})
```

![image](https://user-images.githubusercontent.com/2458896/27049414-3fd8ba22-4f7d-11e7-9040-9983ad8998a7.png)

Maybe try `npm cache clean` or reinstalling the packages?

**Comment by RIP21** [comment] 2017-06-12 19:32
I'm just rerun your test (the only thing I add is import of React at the top, cause it argues without it) 
And the result is exactly as mine. After I delete node_module and reinstall it using `yarn install` I got exactly the same output as before.
Also, I have latest npm 5.0.3 and yarn and node version 8.0.0, and Windows 10 machine which can also be a case.

**Comment by rikukissa** [comment] 2017-06-12 21:43
I noticed the same thing today when I was updating my tests. I have a fix for this, but I'm not 100% sure what is causing it. Currently trying to reproduce this so I'll be able to send a PR.

**Comment by jjanssen** [comment] 2017-06-13 18:05
I have put together a small repository for reproduction at: [https://github.com/jjanssen/jest-styled-components-example](https://github.com/jjanssen/jest-styled-components-example). In this repository is example with a css helper (Example) and just a plain component (Example2). Both of them are tested with `react-test-renderer` and `enzyme` and [both of them fail](https://travis-ci.org/jjanssen/jest-styled-components-example) for each component.

Locally I also applied the change as proposed in PR #27 but this does not yet solve the issue. Right now it feels like the matching of the regular expression is not correct, although I'm not completely sure since I'm not too familiar with the styled-components internals.

**Comment by MicheleBertoli** [comment] 2017-06-13 18:44
Thank you very much @jjanssen, your repo is exactly what we needed.
It looks like in `styled-components` v2.0.1 there's no space anymore between [the class name and the bracket](https://github.com/styled-components/jest-styled-components/blob/master/src/matchers/toHaveStyleRule.js#L51).

**Closed** 2017-06-14 05:37 UTC
