### ISSUE TITLE
Would you consider wrapping the styles in the <style> tag? 

### ISSUE THREAD

**Issue by tomitrescak** [styled-components/jest-styled-components#156] opened 2018-07-08 07:27 UTC
I am rendering HTML preview of snapshots in an extension and it would be very helpful if it would be wrapped in style.

This is current:

https://github.com/styled-components/jest-styled-components/blob/57c488df99598b27bc27da77a356e0d732dccae3/src/styleSheetSerializer.js#L107

This is what I would need

```
let result = `<style>\n${style}${style ? '\n\n' : ''}</style>${code}`
```

Since this is a breaking change, maybe some parameter that would allow to wrap? Thanks.

**Comment by MicheleBertoli** [comment] 2018-07-08 07:49
Duplicate of #135

**Closed by MicheleBertoli** 2018-07-08 07:49 UTC

**Comment by tomitrescak** [comment] 2018-07-08 11:29
It is kind of duplicate, but jest-html renders all kinds of problems. So it is no solution for me. Solving the <style> ... would be the best.
