### ISSUE TITLE
Doesn't work with jsdom

### ISSUE THREAD

**Issue by lgraziani2712** [styled-components/jest-styled-components#2] opened 2017-03-19 14:33 UTC
Enzyme uses jsdom environment to be able to mount components. The following error is thrown by this module.

>  TypeError: Cannot read property 'cssRules' of undefined

Thank you!

**Comment by MicheleBertoli** [comment] 2017-03-19 14:56
That's right @lgraziani2712.
As stated in the [README](https://github.com/styled-components/jest-styled-components#usage), the `testEnvironment` should be set to `node` to make this package work.
You can still use Enzyme's `shallow` rendering.

**Comment by MicheleBertoli** [comment] 2017-03-19 15:51
It would be awesome to have @threepointone's help here :)
It looks like [ownerNode](https://github.com/styled-components/styled-components/blob/master/src/vendor/glamor/sheet.js#L33) is always undefined with `jsdom`

**Comment by lgraziani2712** [comment] 2017-03-19 18:29
Yep, but since didn't see the issue, I reported it! :)

Sorry for not being able to help :(

**Comment by lgraziani2712** [comment] 2017-03-19 18:46
@MicheleBertoli I cannot use `shallow` rendering. At least without changing my tests.

Something as simple as checking if `<Button>Hello!</Button>` renders the text it'll fail if `<Button />` is a `styled.button`. With `shallow` render will happen this:

```jsx
expect('styled.button').toBe('Hello!');
```

**Comment by threepointone** [comment] 2017-03-23 10:28
ola! I'll have a look at this sometime in the next couple of days.

**Comment by MicheleBertoli** [comment] 2017-03-25 07:33
Repro steps:
- clone the repo
- install deps
- [set](https://github.com/styled-components/jest-styled-components/blob/master/package.json#L50) `testEnvironment` to `jsdom`
- run tests
- you get `TypeError: Cannot read property 'cssRules' of undefined`

**Comment by zvictor** [comment] 2017-04-18 16:22
it is caused by a quite old bug in jsdom: https://github.com/tmpvar/jsdom/issues/992

**Comment by MicheleBertoli** [comment] 2017-05-03 20:12
Applying styled-components/styled-components#707 the tests don't break with `jsdom` but the styles are empty. Needs more investigation.

**Comment by zvictor** [comment] 2017-05-03 20:33
> Applying styled-components/styled-components#707 the tests don't break with jsdom but the styles are empty. Needs more investigation.

I ended giving up on styled-components `v1` and moved to `v2.0.0-16+`. The API has totally changed in that version and works better.

**Comment by joseaplwork** [comment] 2017-05-03 22:34
I'm using `styled-components` with `v2.0.0-17` and  `jest-styled-components` with `v2.0.0`
now getting 

`TypeError: styleSheet.rules is not a function`

**Comment by MicheleBertoli** [comment] 2017-05-04 06:16
Thanks @joseaplwork, please check #5.

**Comment by MicheleBertoli** [comment] 2017-05-07 07:06
Jest 20 ships with a [@jest-environment annotation](http://facebook.github.io/jest/blog/2017/05/06/jest-20-delightful-testing-multi-project-runner.html#new-improved-testing-apis) which will make this less annoying.

**Comment by MicheleBertoli** [comment] 2017-05-07 07:18
Jest 20 ships with a [@jest-environment annotation](http://facebook.github.io/jest/blog/2017/05/06/jest-20-delightful-testing-multi-project-runner.html#new-improved-testing-apis) which makes this problem less annoying.
I'm going to close this for now, and we'll get back to it when Styled Components v2 will be stable.

**Closed by MicheleBertoli** 2017-05-07 07:18 UTC

**Comment by MoeSattler** [comment] 2017-05-11 11:36
I think I might not understand this. How does it solve the issue? When my test relies on `jsdom`, `@jest-environment` won't allow me to run a single test magically in both, `node` and `jsdom`.

**Comment by joseaplwork** [comment] 2017-05-11 13:00
@MoeSattler `@jest-environment` is available just in Jest 20, please make sure you are using the right version.
